name: data_shaft
description: High-level data layer for Clean Architecture with standardized Drivers, typed DataSources, and Repository mixins for caching, deduplication, and safe error handling.
version: 1.0.2

homepage: https://github.com/coolosos

repository: https://github.com/coolosos/data_shaft
issue_tracker: https://github.com/coolosos/data_shaft/issues

topics:
  - data
  - clean-architecture
  - repository
  - abstraction
  - architecture

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  meta: ^1.17.0
  cool_bedrock: ^1.0.0

dev_dependencies:
  coolint: 2.1.2
  test: ^1.28.0
