name: data_shaft
description: Cornerstone for building a robust and decoupled Data Layer within a Clean Architecture setup. This package provides all the essential abstractions (interfaces and base models) required to define the contract of the Data Layer, without concerning itself with concrete implementation details.
version: 1.0.0

homepage: https://github.com/coolosos

repository: https://github.com/coolosos/data_shaft
issue_tracker: https://github.com/coolosos/data_shaft/issues

topics:
  - data
  - clean-architecture
  - repository
  - abstraction
  - core

environment:
  sdk: ^3.8.1

dependencies:
  meta: any
  cool_bedrock: 1.0.0

dev_dependencies:
  coolint: any
  test: any
